address: "0.0.0.0:8080"
cooldown: 20s
max_chan: 10

group:
  group1:
    address: ["http://serv1:8081", "http://serv2:8082", "http://serv3:8083"]
    cooldown: 5s
    batch_size: 10
    retry: 3

  group2:
    address: ["http://serv1:8081", "http://serv2:8082"]
    cooldown: 5s
    batch_size: 15
    retry: 3

  group3:
    address: ["http://serv3:8083"]
    cooldown: 5s
    batch_size: 20
    retry: 3